language: rust
dist: trusty
rust:
  - nightly
  - beta
  - stable

addons:
  chrome: stable

before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

script:
  - cargo build -v
  - cargo test -v
  - cargo bench -v
  - cargo doc -v

notifications:
  email:
    on_success: never
