language: rust
rust:
  - nightly
  - beta
  - stable
os:
  - linux
  - osx

script:
  - cargo build -v
  - cargo test -v
  - cargo bench -v
  - cargo doc -v

notifications:
  email:
    on_success: never
